[package]
name = "ocean-visualizations"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
bevy.workspace = true
bevy-screenshot-harness = { path = "../harness" }

[[example]]
name = "cube"
